// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Emision_Seguros.Data;

#nullable disable

namespace Sistema_Emision_Seguros.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621183702_PrimeraMigracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Emision_Seguros.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Sistema_Emision_Seguros.Models.Cobertura", b =>
                {
                    b.Property<int>("IdCobertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCobertura"));

                    b.Property<decimal>("MontoCobertura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreCobertura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCobertura");

                    b.ToTable("Coberturas");
                });

            modelBuilder.Entity("Sistema_Emision_Seguros.Models.Poliza", b =>
                {
                    b.Property<int>("IdPoliza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPoliza"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("NumeroPoliza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrimaTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SumaAsegurada")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPoliza");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Polizas");
                });

            modelBuilder.Entity("Sistema_Emision_Seguros.Models.PolizaCobertura", b =>
                {
                    b.Property<int>("IdPoliza")
                        .HasColumnType("int");

                    b.Property<int>("IdCobertura")
                        .HasColumnType("int");

                    b.HasKey("IdPoliza", "IdCobertura");

                    b.HasIndex("IdCobertura");

                    b.ToTable("PolizasCoberturas");
                });

            modelBuilder.Entity("Sistema_Emision_Seguros.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int>("AnioFabricacion")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValorComercial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdVehiculo");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Sistema_Emision_Seguros.Models.Poliza", b =>
                {
                    b.HasOne("Sistema_Emision_Seguros.Models.Cliente", "Cliente")
                        .WithMany("Polizas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Emision_Seguros.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Sistema_Emision_Seguros.Models.PolizaCobertura", b =>
                {
                    b.HasOne("Sistema_Emision_Seguros.Models.Cobertura", "Cobertura")
                        .WithMany("PolizasCoberturas")
                        .HasForeignKey("IdCobertura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistema_Emision_Seguros.Models.Poliza", "Poliza")
                        .WithMany("PolizasCoberturas")
                        .HasForeignKey("IdPoliza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobertura");

                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("Sistema_Emision_Seguros.Models.Cliente", b =>
                {
                    b.Navigation("Polizas");
                });

            modelBuilder.Entity("Sistema_Emision_Seguros.Models.Cobertura", b =>
                {
                    b.Navigation("PolizasCoberturas");
                });

            modelBuilder.Entity("Sistema_Emision_Seguros.Models.Poliza", b =>
                {
                    b.Navigation("PolizasCoberturas");
                });
#pragma warning restore 612, 618
        }
    }
}
